baseURL = "https://sotirismorf.github.io/thmmy-notes/"
locale = 'el'
title = 'THMMY notes - sotirismorf'
disableKinds = ['taxonomy', 'term']

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
    [markup.goldmark.renderer]
    unsafe = true
